### ISSUE TITLE
Update module to use paths from https://github.com/linux-surface

### ISSUE THREAD

**Issue by shadowrylander** [anthe/nixos-surface#1] opened 2020-05-17 00:49 UTC
Hello! First issue! ... Sorry about that... 😹 

I was wondering if you would be able to update the module regarding paths a bit, as `qzed's` modifications are now at [`Linux Surface`](https://github.com/linux-surface); I would do it myself, but I'm still incredibly new to this, so I've no idea where to even begin.

In trying to build an `iso` with the module, using `sudo nix-build -A config.system.build.isoImage -I nixos-config=modules/installer/cd-dvd/installation-cd-graphical-gnome.nix default.nix
`, on an `Arch Linux` Linode VPS with `nix` installed, and importing it in `nixpkgs/nixos/modules/profiles/base.nix`, I am coming across the following warning and error:
```bash
warning: the group 'nixbld' specified in 'build-users-group' does not exist
error: opening file '/home/shadowrylander/nixpkgs/nixos/modules/profiles/nixos-surface/linux-surface/root/etc/NetworkManager/conf.d/99-surface.conf': No such file or directory
```

I tried with `qzed's` repo path, and then with the `linux-surface` repo paths, but neither worked; I modified and updated the `nixos-surface` submodule paths using the following:
```bash
git submodule sync
git submodule update --force --recursive --init --remote
```
The current `.gitmodules` file is this:
```
[submodule "libwacom-surface"]
        path = libwacom-surface
        url = https://github.com/linux-surface/libwacom-surface
[submodule "linux-surface-kernel-configs"]
        path = linux-surface-kernel-configs
        url = https://github.com/linux-surface/linux-surface-kernel-configs
[submodule "linux-surface"]
        path = linux-surface
        url = https://github.com/linux-surface/linux-surface
[submodule "kernel-configs"]
        path = kernel-configs
        url = https://github.com/linux-surface/kernel-configs
```

Any help would be greatly appreciated!

`P.S. : ` Clicking on the submodule link for `linux-surface` give a `404` error page in GitHub!

**Comment by anthe** [comment] 2020-05-17 01:17
I've made a lot of changes that I haven't pushed. I generally think that no one is using this so I don't bother to keep it up to date, but that's clearly wrong! I'll push my changes probably later today.

**Comment by shadowrylander** [comment] 2020-05-17 01:23
Help me, Anthe-Wan Kenobi; you're my only hope! ... For a NixOS ZFS Surface Book 2! 😻😹

I greatly appreciate the help!

**Comment by shadowrylander** [comment] 2020-05-17 06:06
Quick note:

I am now getting the following error:
```bash
error: function `callPackages` was called on a *single* derivation "surface-dtx-daemon-0.1.4-3"; did you mean to use `callPackage` instead?
```

**Comment by anthe** [comment] 2020-05-17 07:15
All my changes are pushed now, so let me know how it goes.

**Comment by shadowrylander** [comment] 2020-05-17 07:16
Will do! Just need to boot into a live environment, and I'll let you know!

**Comment by shadowrylander** [comment] 2020-05-17 08:43
Building using this:
```bash
nix-build -A config.system.build.isoImage -I nixos-config=modules/installer/cd-dvd/installation-cd-graphical-gnome.nix default.nix
```
fails with this:
```make
hash mismatch in fixed-output derivation '/nix/store/1ixksjxpjf6j7pnmsyakywl2i2ysb8km-surface-control-0.2.5-3-vendor.tar.gz':
  wanted: sha256:0zq0nqlvzvgzrgr3cx5gbd2x2n3pdzxp1xsy6jhkyk8ap4cr9jp9
  got:    sha256:01ld3xsl2vzy2sy4w5qsl67y155f87gqn30i1z97j13na3gilsnk
cannot build derivation '/nix/store/wrm7kdlf16janak3b5jy6gzpf1nnm5gw-surface-control-0.2.5-3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8pf5rxy61kz4y8bd05bw0apj24lpk51s-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/62bayf2fsr11zf4gnins1136pliryz6k-nixos-system-nixos-20.09pre-git.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/k5clmslcj516c3v7h7js4y7zn3bn2rji-closure-info.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4q4d3dprv5vq2gsi4203jbd9szykp915-efi-directory.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qip34v3hha4d1ym7pgx1zgmlkp6fr09a-isolinux.cfg-in.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s5vc0bl17n8qr79r2cq60w964am85i2a-nixos-20.09pre-git-x86_64-linux.iso.drv': 1 dependencies couldn't be built
error: build of '/nix/store/s5vc0bl17n8qr79r2cq60w964am85i2a-nixos-20.09pre-git-x86_64-linux.iso.drv' failed
```

**Comment by anthe** [comment] 2020-05-17 17:03
So that's a mismatch of the cargo hash which means we have some difference in which particular rust packages we're using. Are you on nixos-20.03? sudo nix-channel --list will show which nixos channel you're on.

**Comment by shadowrylander** [comment] 2020-05-17 17:30
Will the command be any different if I'm in a live environment?

**Comment by anthe** [comment] 2020-05-17 17:33
I don't think so. I guess the next question is are you using the 20.03 nixos iso to boot up the live environment?

**Comment by shadowrylander** [comment] 2020-05-17 17:44
No, 20.09; would that make a difference? I'm also on the Unstable channel, _only_.

**Comment by anthe** [comment] 2020-05-17 17:53
Yeah, that's probably what's causing the problem. You could switch to 20.03, or change the sha256 hash to match your system. That's one of the standard ways to solve this problem: https://nixos.org/nixpkgs/manual/#compiling-rust-applications-with-cargo

You'll have to change the cargoSha256 in surface-control.nix and surface-dtx-daemon.nix

**Comment by shadowrylander** [comment] 2020-05-17 18:16
So I'd just have to replace the sha256 checksum in surface-dtx-daemon.nix with the [exact] one in the documentation?

**Comment by shadowrylander** [comment] 2020-05-17 18:19
Also, silly question: how do I get the 20.09 manual? My searches only reveal the 20.03 instance.

**Comment by anthe** [comment] 2020-05-17 19:20
You'd replace the cargoSha256 checksum with the one after "got:" in the failed build.
So in your case for surface-control: 01ld3xsl2vzy2sy4w5qsl67y155f87gqn30i1z97j13na3gilsnk

I'm not sure how to find documentation for 20.09, but usually not too much changes, so 20.03 should work for most things.

**Comment by shadowrylander** [comment] 2020-05-17 19:34
Ah; perfect! I'll get right on it.

**Comment by shadowrylander** [comment] 2020-05-18 04:43
It keeps saying there's no space left on the device; I think there's a max size to the iso or similar, as I'm using a 64 GB USB love environment. I'll set this up in an install instead; I just have to put it in my `configuration.nix`, correct?

**Comment by shadowrylander** [comment] 2020-05-18 04:43
Also, still new to nix: ... Where is the configuration.nix file located again? 😅

**Comment by anthe** [comment] 2020-05-18 04:55
Yeah, that's how I set it up. I did a normal install, then after I got it booting I added nixos-surface to /etc/nixos/configuration.nix 
Definitely just get a basic installation working and booting on your machine before adding nixos-surface.

**Comment by shadowrylander** [comment] 2020-05-18 05:26
Sounds about the way to go. I'll try to get it up and running in the next few days and report back; I'll leave this open in the meantime?

**Comment by shadowrylander** [comment] 2020-05-19 00:46
Quick question: does this work with a ZFS root? Or does it require a dkms module?

**Comment by anthe** [comment] 2020-05-19 18:11
I don't know, but it looks like maybe NixOS supports ZFS out of the box: https://nixos.org/nixos/options.html#zfs
Try adding boot.loader.grub.zfsSupport=true; to your configuration.nix

**Comment by shadowrylander** [comment] 2020-05-19 18:17
Fair enough! I'll try out the zfs root manual and report back.

**Comment by shadowrylander** [comment] 2020-05-20 04:30
After stripping a bunch of paths, I get this while building:
```make
builder for '/nix/store/jk52nwwkv0aabzwmn4ldrvs1lm8jl0wv-surface-dtx-daemon-0.1.4-3.drv' failed with exit code 101
cannot build derivation '/nix/store/zjmj4rpc8kpnprz83g9vybszsm5yrdbh-dbus-1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1dll604a616i79v44i4br58yxlp52d7v-hwdb.bin.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/y59avcb1kjqsng065ciyya1x094gfc0g-system-generators.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/mr404ma9xb9692n3myly7gm77imbvfmw-system-shutdown.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vrzcaqvgm3hvbkmmyh6awlk5naw0ghk0-system-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fj9fjhs78kgqpf8a156dh2yqg2w99l3h-udev-rules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/cdk5wv9nrh07gmnfpghqcdrivcyrd7k0-user-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6jjf4y4rj1ayj7qnq06kxxyx0lg0pfnv-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/80hjjwk66ixdanfp675268zaz5ykvbn3-nixos-system-nixos-20.09pre-git.drv': 1 dependencies couldn't be built
error: build of '/nix/store/80hjjwk66ixdanfp675268zaz5ykvbn3-nixos-system-nixos-20.09pre-git.drv' failed
```
Do I have to update rust and reboot (apparently)? Or is the package itself incorrectly configured?

**Comment by anthe** [comment] 2020-05-20 19:49
I'm not really sure. Exit code 101 is a timeout error and I think by default there is no timeout, so maybe you set one, but presumably you had a reason to do that. I might be able to help more if I got a look at the build log and nix file.

**Comment by shadowrylander** [comment] 2020-05-20 19:59
Ah; of course. Here is the daemon file, where I changed the cargo checksum: https://www.github.com/shadowrylander/nixos-surface/tree/master/surface-dtx-daemon.nix

And here are the options, which I did not modify: https://www.github.com/shadowrylander/nixos-surface/tree/master/surface-dtx-daemon-options.nix

Where can I get the build log from?

**Comment by anthe** [comment] 2020-05-20 20:24
Would build_command | tee build_log work?

**Comment by shadowrylander** [comment] 2020-05-20 20:38
Ah, so the entire command output? On it.

**Comment by shadowrylander** [comment] 2020-05-20 21:06
Well, `tee` didn't work, but redirecting the output did!
[log.txt](https://github.com/anthe/nixos-surface/files/4659289/log.txt)

**Comment by anthe** [comment] 2020-05-20 21:34
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /build/surface-dtx-daemon-0.1.4-3-vendor.tar.gz/libdbus-sys/build.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

That looks like the relevant line to me. I'm not exactly sure what's going on, if you put RUST_BACKTRACE=1 into the surface-dtx nix file I think that will give you more information. Is nixos-20.03 out of the question?

**Comment by shadowrylander** [comment] 2020-05-20 21:39
Not at all; but since I'm building a gnome iso off the master nixpkgs branch, due to my having a Surface Book 2 and seemingly no other DE supports the device's HiDPI out of the box, I haven't got many options. I'm assuming 20.03 will have a branch in the repo, right?

**Comment by shadowrylander** [comment] 2020-05-20 21:41
Got it; `release-20.03`. I'll see if I can build a gnome iso off that!

**Comment by shadowrylander** [comment] 2020-05-21 04:54
Got this while installing and then rebooting with the surface module:
```
modprobe: FATAL: Module surface_acpi not found in directory /lib/modules/4.19.123
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)
```
Currently trying to configure the surface module after installing NixOS. 

Edit: whoops; didn't change the release version.

**Comment by shadowrylander** [comment] 2020-05-21 05:08
Changing the release version and configuring the module while installing and rebooting did not work either. Still attempting to install and then configure.

**Comment by shadowrylander** [comment] 2020-05-21 05:20
That didn't work either; same error as in https://github.com/anthe/nixos-surface/issues/1#issuecomment-631879111.

**Comment by anthe** [comment] 2020-05-21 06:09
I haven't built a custom nixos iso, and I'm wondering if you're running into extra trouble because of it. Have you tried installing one of the standard nixos ISOs on your surface device, then adding gnome and nixos-surface after you have nixos booting?

**Comment by shadowrylander** [comment] 2020-05-21 06:34
I unfortunately can't see anything then; everything is really bloody small. I can try, however; do I have to wipe my previous build, though? I.e. start over?

**Comment by shadowrylander** [comment] 2020-05-21 10:06
Well, without clearing out the previous install, neither installing it with the module and rebooting, not installing it without and building it, worked.

**Comment by shadowrylander** [comment] 2020-05-21 10:14
If I _should_ clear out the previous install, which directories should I remove?

**Comment by shadowrylander** [comment] 2020-05-21 10:31
Also, I am using a ZFS root with encryption on the entire pool, so I'm not sure if that's helping. Or wait... I clear out my entire root partition every time I boot up; while that may explain the surface module failing to load, it wouldn't explain the ZFS insertion error, as that works even if the root is cleared out, but never when using the surface module.

**Comment by shadowrylander** [comment] 2020-05-21 10:32
Root is cleared out using this method: https://grahamc.com/blog/erase-your-darlings

**Comment by anthe** [comment] 2020-05-21 18:12
Maybe it's worth figuring out ZFS, root encryption, root clearing and nixos-surface separately, it's a lot to get working all at once.
Can you post the errors in dmesg that show up when you try to load zfs?
I don't think starting over is necessary. If you have nixos installed, to get everything working is in principle just a matter of figuring what should go in your configuration.nix. Though that's definitely not always trivial.

**Comment by shadowrylander** [comment] 2020-05-21 19:39
Fair enough! Unfortunately, I can't even boot up into a shell when the problem occurs, so I'm not sure how to get it otherwise.

**Comment by shadowrylander** [comment] 2020-05-24 00:05
Would you happen to know if it's possible to reverse the order in which the surface and zfs modules are loaded? Such as putting the boot option for zfs before the imports statement?

**Comment by anthe** [comment] 2020-05-24 02:37
I'm not sure about controlling the order, but you'll need boot.initrd.kernelModules to have zfs in there for sure. I'd expect that when you enabled the zfs options that was added automatically, but maybe not. The surface modules are probably fine to load anytime.

**Comment by shadowrylander** [comment] 2020-05-24 08:42
It would appear as though zfs isn't building properly for the surface module; what I usually do on other distributions is use the `zfs-dkms` package, but that doesn't seem to be an option for `NixOS`; do you know any way I could tailor the zfs module specifically for your surface module?

**Comment by anthe** [comment] 2020-05-24 15:57
Here's how to add kernel modules on nixos:
`boot.extraModulePackages = (with config.boot.kernelPackages; [ zfs ]);`
This will build the zfs module for the kernel you're using, surface or not.

**Comment by shadowrylander** [comment] 2020-05-24 16:53
Could you possibly go over my configuration.nix file to see if I got it right? It seems there may be redundant statements in there due to following both your instructions and the NixOS instructions.

**Comment by shadowrylander** [comment] 2020-05-24 18:36
Also, `boot.extraModulePackages = (with config.boot.kernelPackages; [ zfs ]);` did not work either.

**Comment by shadowrylander** [comment] 2020-05-24 21:27
[configuration.txt](https://github.com/anthe/nixos-surface/files/4674436/configuration.txt)

**Comment by shadowrylander** [comment] 2020-05-25 22:36
'Ello?

**Comment by anthe** [comment] 2020-05-25 23:52
Your `configuration.nix` looks right to me. Does your machine boot if you don't include `surface.nix`? If not, then you're probably still dealing with encrypted root and zfs problems.
I think you can change the console font to fix the size problem. I don't think my changes are going to fix the font problem.

**Comment by shadowrylander** [comment] 2020-05-26 05:38
It boots just fine without your module, but the primary reason for using it is basically the touchscreen, the docking setup, suspending, and overheating issues without it. At least, that's what I gathered from using the live install without your module.

**Comment by anthe** [comment] 2020-05-26 20:10
Yeah, those are all the reasons linux-surface is necessary. 
I should have asked my question more precisely. Do you have nixos installed on your machine with zfs and the encrypted root? And then when you add `surface.nix` does it break? From your last comment it sounds like you've had only the live environment booted.
Another thing to try is an installation on unencrypted ext4 with `surface.nix`imported just to be sure my changes are working on your end.

**Comment by shadowrylander** [comment] 2020-05-26 21:31
Okay, so basically I'm running NixOS off an external SSD; encrypted zfs root works, until I rebuild with your module and it seems to break the setup. Without your module, the new generation then starts working again.

Quick note, however: I've changed my IT setup a bit, such that I don't entirely need the module anymore; not to mention I really need ZFS... And I've reformatted my drive so many times now I'm afraid I might damage it if I do it any more. 😅

**Comment by anthe** [comment] 2020-05-27 03:07
So I've confirmed your problem on my end, I also can't load the zfs module. I've narrowed the problem down to the linux-surface patches. I'm not inclined to do all the compiling necessary to binary search for the particular patch that is causing the problem. I have other things I need my cpu cycles for.
I'm using kernel 4.19 since all the other kernel versions available on 20.03 break the touchscreen. Soon enough I should be able to use a more recent kernel, and we can hope that the zfs problem will be fixed there. 
You could also try raising the issue over at linux-surface. If other people on other distros are having trouble with zfs there might be enough interest in fixing the problem.

**Comment by shadowrylander** [comment] 2020-05-27 03:14
If I remember correctly, the last Surface LTS kernel was the only one reliable enough to work with the zfs-dkms module, so I'm not as sure about a kernel upgrade. In addition, I'm also not sure enough people are using NixOS, as their install instructions for the OS lead to a 404 error.

Ah well. Maybe some time in the future.

Thank you very, very much for all the help on the matter! Shall I go ahead and close the issue, then?

**Comment by anthe** [comment] 2020-05-27 03:22
I'm happy to help, and I'm sorry we couldn't get it working for you.

**Comment by shadowrylander** [comment] 2020-05-27 03:23
Not a problem! Can't have everything, unfortunately. Sigh... 😹

**Closed as completed by anthe** 2020-05-27 03:22 UTC
